import { CulturalArchetype, OceanTraits } from '../types/psychometrics';

export interface ArchetypeProfile extends CulturalArchetype {
  readonly traits: OceanTraits;
}

export const CULTURAL_ARCHETYPES_CATALOG: readonly ArchetypeProfile[] = [
  // Ficticios
  {
    id: 'char_tyler_durden',
    name: 'Tyler Durden',
    origin: 'Fight Club',
    type: 'fictional',
    affinityPercentage: 91.2,
    sharedTraits: ['Ruptura de convención', 'Energía visceral', 'Desafío al canon'],
    avatarUrl: '/assets/archetypes/tyler.webp',
    traits: {
      openness: 85,
      conscientiousness: 35,
      extraversion: 75,
      agreeableness: 30,
      neuroticism: 80,
    },
  },
  {
    id: 'char_sherlock_holmes',
    name: 'Sherlock Holmes',
    origin: 'Arthur Conan Doyle',
    type: 'fictional',
    affinityPercentage: 88.0,
    sharedTraits: ['Rigor analítico', 'Observación deductiva', 'Desapego'],
    avatarUrl: '/assets/archetypes/sherlock.webp',
    traits: {
      openness: 90,
      conscientiousness: 95,
      extraversion: 25,
      agreeableness: 35,
      neuroticism: 40,
    },
  },
  {
    id: 'char_amelie_poulain',
    name: 'Amélie Poulain',
    origin: "Le Fabuleux Destin d'Amélie Poulain",
    type: 'fictional',
    affinityPercentage: 89.4,
    sharedTraits: ['Idealismo poético', 'Altruismo silencioso', 'Imaginación'],
    avatarUrl: '/assets/archetypes/amelie.webp',
    traits: {
      openness: 95,
      conscientiousness: 70,
      extraversion: 30,
      agreeableness: 90,
      neuroticism: 60,
    },
  },
  {
    id: 'char_holden_caulfield',
    name: 'Holden Caulfield',
    origin: 'The Catcher in the Rye',
    type: 'fictional',
    affinityPercentage: 85.7,
    sharedTraits: ['Escepticismo existencial', 'Vulnerabilidad oculta', 'Rebeldía'],
    avatarUrl: '/assets/archetypes/holden.webp',
    traits: {
      openness: 80,
      conscientiousness: 30,
      extraversion: 40,
      agreeableness: 45,
      neuroticism: 85,
    },
  },
  {
    id: 'char_neo',
    name: 'Neo (Thomas Anderson)',
    origin: 'The Matrix',
    type: 'fictional',
    affinityPercentage: 87.5,
    sharedTraits: ['Despertar de consciencia', 'Firmeza ante el destino', 'Trascendencia'],
    avatarUrl: '/assets/archetypes/neo.webp',
    traits: {
      openness: 92,
      conscientiousness: 75,
      extraversion: 35,
      agreeableness: 60,
      neuroticism: 55,
    },
  },
  {
    id: 'char_atticus_finch',
    name: 'Atticus Finch',
    origin: 'To Kill a Mockingbird',
    type: 'fictional',
    affinityPercentage: 90.1,
    sharedTraits: ['Integridad inquebrantable', 'Justicia compasiva', 'Serenidad'],
    avatarUrl: '/assets/archetypes/atticus.webp',
    traits: {
      openness: 85,
      conscientiousness: 90,
      extraversion: 50,
      agreeableness: 95,
      neuroticism: 25,
    },
  },
  {
    id: 'char_rick_blaine',
    name: 'Rick Blaine',
    origin: 'Casablanca',
    type: 'fictional',
    affinityPercentage: 86.3,
    sharedTraits: ['Cinismo aparente', 'Nobleza de fondo', 'Estoicismo romántico'],
    avatarUrl: '/assets/archetypes/rick_blaine.webp',
    traits: {
      openness: 70,
      conscientiousness: 80,
      extraversion: 45,
      agreeableness: 55,
      neuroticism: 65,
    },
  },
  {
    id: 'char_elizabeth_bennet',
    name: 'Elizabeth Bennet',
    origin: 'Pride and Prejudice',
    type: 'fictional',
    affinityPercentage: 88.9,
    sharedTraits: ['Agudeza verbal', 'Autonomía intelectual', 'Perspicacia'],
    avatarUrl: '/assets/archetypes/elizabeth.webp',
    traits: {
      openness: 85,
      conscientiousness: 70,
      extraversion: 65,
      agreeableness: 70,
      neuroticism: 45,
    },
  },
  {
    id: 'char_walter_white',
    name: 'Walter White',
    origin: 'Breaking Bad',
    type: 'fictional',
    affinityPercentage: 83.2,
    sharedTraits: ['Metodología implacable', 'Orgullo latente', 'Transformación radical'],
    avatarUrl: '/assets/archetypes/walter.webp',
    traits: {
      openness: 80,
      conscientiousness: 95,
      extraversion: 30,
      agreeableness: 20,
      neuroticism: 80,
    },
  },
  {
    id: 'char_don_quijote',
    name: 'Don Quijote de la Mancha',
    origin: 'Miguel de Cervantes',
    type: 'fictional',
    affinityPercentage: 92.5,
    sharedTraits: ['Idealismo utópico', 'Pasión heroica', 'Desafío a la realidad gris'],
    avatarUrl: '/assets/archetypes/quijote.webp',
    traits: {
      openness: 98,
      conscientiousness: 50,
      extraversion: 70,
      agreeableness: 75,
      neuroticism: 70,
    },
  },
  {
    id: 'char_jay_gatsby',
    name: 'Jay Gatsby',
    origin: 'The Great Gatsby',
    type: 'fictional',
    affinityPercentage: 84.1,
    sharedTraits: ['Anhelo nostálgico', 'Grandeza teatral', 'Fidelidad a un sueño'],
    avatarUrl: '/assets/archetypes/gatsby.webp',
    traits: {
      openness: 80,
      conscientiousness: 60,
      extraversion: 75,
      agreeableness: 60,
      neuroticism: 75,
    },
  },
  {
    id: 'char_lisbeth_salander',
    name: 'Lisbeth Salander',
    origin: 'Millennium',
    type: 'fictional',
    affinityPercentage: 89.0,
    sharedTraits: ['Ciberjusticia férrea', 'Resiliencia extrema', 'Hermetismo'],
    avatarUrl: '/assets/archetypes/lisbeth.webp',
    traits: {
      openness: 85,
      conscientiousness: 85,
      extraversion: 15,
      agreeableness: 25,
      neuroticism: 75,
    },
  },
  {
    id: 'char_severus_snape',
    name: 'Severus Snape',
    origin: 'Harry Potter',
    type: 'fictional',
    affinityPercentage: 85.0,
    sharedTraits: ['Lealtad trágica', 'Ocultación metódica', 'Intensidad reprimida'],
    avatarUrl: '/assets/archetypes/snape.webp',
    traits: {
      openness: 75,
      conscientiousness: 90,
      extraversion: 15,
      agreeableness: 25,
      neuroticism: 85,
    },
  },
  {
    id: 'char_ellen_ripley',
    name: 'Ellen Ripley',
    origin: 'Alien',
    type: 'fictional',
    affinityPercentage: 91.0,
    sharedTraits: ['Instinto de supervivencia', 'Liderazgo bajo crisis', 'Pragmatismo'],
    avatarUrl: '/assets/archetypes/ripley.webp',
    traits: {
      openness: 70,
      conscientiousness: 95,
      extraversion: 55,
      agreeableness: 65,
      neuroticism: 35,
    },
  },
  {
    id: 'char_gandalf',
    name: 'Gandalf el Gris',
    origin: 'The Lord of the Rings',
    type: 'fictional',
    affinityPercentage: 93.4,
    sharedTraits: ['Sabiduría ancestral', 'Paciencia orientadora', 'Humildad protectora'],
    avatarUrl: '/assets/archetypes/gandalf.webp',
    traits: {
      openness: 95,
      conscientiousness: 85,
      extraversion: 60,
      agreeableness: 85,
      neuroticism: 25,
    },
  },
  {
    id: 'char_rust_cohle',
    name: 'Rustin Cohle',
    origin: 'True Detective',
    type: 'fictional',
    affinityPercentage: 90.7,
    sharedTraits: ['Pesimismo lúcido', 'Obsesión investigativa', 'Percepción despojada'],
    avatarUrl: '/assets/archetypes/rust.webp',
    traits: {
      openness: 90,
      conscientiousness: 85,
      extraversion: 20,
      agreeableness: 30,
      neuroticism: 85,
    },
  },
  {
    id: 'char_clara_del_valle',
    name: 'Clara del Valle',
    origin: 'La Casa de los Espíritus',
    type: 'fictional',
    affinityPercentage: 88.3,
    sharedTraits: ['Sensibilidad extrasensorial', 'Paz interior', 'Conexión espiritual'],
    avatarUrl: '/assets/archetypes/clara.webp',
    traits: {
      openness: 95,
      conscientiousness: 60,
      extraversion: 40,
      agreeableness: 90,
      neuroticism: 40,
    },
  },
  {
    id: 'char_edmond_dantes',
    name: 'Edmón Dantès',
    origin: 'Le Comte de Monte-Cristo',
    type: 'fictional',
    affinityPercentage: 87.2,
    sharedTraits: ['Paciencia calculadora', 'Justicia retributiva', 'Elegancia gélida'],
    avatarUrl: '/assets/archetypes/dantes.webp',
    traits: {
      openness: 85,
      conscientiousness: 95,
      extraversion: 45,
      agreeableness: 35,
      neuroticism: 65,
    },
  },
  {
    id: 'char_spock',
    name: 'Mr. Spock',
    origin: 'Star Trek',
    type: 'fictional',
    affinityPercentage: 89.8,
    sharedTraits: ['Lógica pura', 'Equilibrio emocional contenido', 'Lealtad ética'],
    avatarUrl: '/assets/archetypes/spock.webp',
    traits: {
      openness: 85,
      conscientiousness: 98,
      extraversion: 25,
      agreeableness: 60,
      neuroticism: 15,
    },
  },
  {
    id: 'char_jo_march',
    name: 'Jo March',
    origin: 'Little Women',
    type: 'fictional',
    affinityPercentage: 90.5,
    sharedTraits: ['Independencia feroz', 'Fuego creativo', 'Generosidad fraterna'],
    avatarUrl: '/assets/archetypes/jo.webp',
    traits: {
      openness: 92,
      conscientiousness: 70,
      extraversion: 75,
      agreeableness: 80,
      neuroticism: 55,
    },
  },
  {
    id: 'char_raskolnikov',
    name: 'Rodión Raskólnikov',
    origin: 'Crimen y Castigo',
    type: 'fictional',
    affinityPercentage: 82.6,
    sharedTraits: ['Remordimiento ético', 'Dualidad interior', 'Búsqueda de redención'],
    avatarUrl: '/assets/archetypes/raskolnikov.webp',
    traits: {
      openness: 85,
      conscientiousness: 40,
      extraversion: 25,
      agreeableness: 40,
      neuroticism: 95,
    },
  },
  {
    id: 'char_mulder',
    name: 'Fox Mulder',
    origin: 'The X-Files',
    type: 'fictional',
    affinityPercentage: 88.2,
    sharedTraits: ['Curiosidad insobornable', 'Fe en lo invisible', 'Dedicación absoluta'],
    avatarUrl: '/assets/archetypes/mulder.webp',
    traits: {
      openness: 95,
      conscientiousness: 65,
      extraversion: 50,
      agreeableness: 65,
      neuroticism: 70,
    },
  },
  {
    id: 'char_samwise',
    name: 'Samwise Gamgee',
    origin: 'The Lord of the Rings',
    type: 'fictional',
    affinityPercentage: 94.0,
    sharedTraits: ['Devoción incondicional', 'Nobleza sencilla', 'Coraje inadvertido'],
    avatarUrl: '/assets/archetypes/samwise.webp',
    traits: {
      openness: 60,
      conscientiousness: 95,
      extraversion: 55,
      agreeableness: 98,
      neuroticism: 30,
    },
  },
  {
    id: 'char_beatrix_kido',
    name: 'Beatrix Kiddo (The Bride)',
    origin: 'Kill Bill',
    type: 'fictional',
    affinityPercentage: 86.9,
    sharedTraits: ['Determinación inmutable', 'Fuerza marcial', 'Protección maternal'],
    avatarUrl: '/assets/archetypes/beatrix.webp',
    traits: {
      openness: 65,
      conscientiousness: 90,
      extraversion: 50,
      agreeableness: 30,
      neuroticism: 60,
    },
  },
  {
    id: 'char_don_draper',
    name: 'Don Draper',
    origin: 'Mad Men',
    type: 'fictional',
    affinityPercentage: 84.5,
    sharedTraits: ['Carisma enigmático', 'Creatividad publicitaria', 'Soledad interna'],
    avatarUrl: '/assets/archetypes/draper.webp',
    traits: {
      openness: 85,
      conscientiousness: 75,
      extraversion: 70,
      agreeableness: 40,
      neuroticism: 75,
    },
  },

  // Históricos
  {
    id: 'char_leonardo_da_vinci',
    name: 'Leonardo da Vinci',
    origin: 'Renacimiento Italiano',
    type: 'historical',
    affinityPercentage: 95.8,
    sharedTraits: ['Curiosidad universal', 'Polimatía', 'Observación de la naturaleza'],
    avatarUrl: '/assets/archetypes/davinci.webp',
    traits: {
      openness: 100,
      conscientiousness: 75,
      extraversion: 55,
      agreeableness: 70,
      neuroticism: 30,
    },
  },
  {
    id: 'char_nikola_tesla',
    name: 'Nikola Tesla',
    origin: 'Inventor e Ingeniero',
    type: 'historical',
    affinityPercentage: 92.3,
    sharedTraits: ['Visión electromagnética', 'Vanguardismo desinteresado', 'Ascetismo'],
    avatarUrl: '/assets/archetypes/tesla.webp',
    traits: {
      openness: 98,
      conscientiousness: 90,
      extraversion: 20,
      agreeableness: 60,
      neuroticism: 65,
    },
  },
  {
    id: 'char_frida_kahlo',
    name: 'Frida Kahlo',
    origin: 'Pintora Mexicana',
    type: 'historical',
    affinityPercentage: 91.7,
    sharedTraits: ['Autenticidad descarnada', 'Resiliencia corporal', 'Color visceral'],
    avatarUrl: '/assets/archetypes/frida.webp',
    traits: {
      openness: 95,
      conscientiousness: 60,
      extraversion: 70,
      agreeableness: 60,
      neuroticism: 85,
    },
  },
  {
    id: 'char_david_bowie',
    name: 'David Bowie',
    origin: 'Músico y Camaleón Cultural',
    type: 'historical',
    affinityPercentage: 94.2,
    sharedTraits: ['Metamorfosis artística', 'Estética futurista', 'Vanguardia sonora'],
    avatarUrl: '/assets/archetypes/bowie.webp',
    traits: {
      openness: 98,
      conscientiousness: 75,
      extraversion: 85,
      agreeableness: 70,
      neuroticism: 50,
    },
  },
  {
    id: 'char_virginia_woolf',
    name: 'Virginia Woolf',
    origin: 'Escritora Modernista',
    type: 'historical',
    affinityPercentage: 90.4,
    sharedTraits: ['Corriente de la conciencia', 'Sensibilidad estética', 'Profundidad lírica'],
    avatarUrl: '/assets/archetypes/woolf.webp',
    traits: {
      openness: 96,
      conscientiousness: 65,
      extraversion: 30,
      agreeableness: 65,
      neuroticism: 90,
    },
  },
  {
    id: 'char_alan_turing',
    name: 'Alan Turing',
    origin: 'Padre de la Computación',
    type: 'historical',
    affinityPercentage: 93.1,
    sharedTraits: ['Genio abstracto', 'Heroísmo silencioso', 'Rigor criptográfico'],
    avatarUrl: '/assets/archetypes/turing.webp',
    traits: {
      openness: 95,
      conscientiousness: 92,
      extraversion: 20,
      agreeableness: 65,
      neuroticism: 45,
    },
  },
  {
    id: 'char_marie_curie',
    name: 'Marie Curie',
    origin: 'Pionera de la Radiactividad',
    type: 'historical',
    affinityPercentage: 92.8,
    sharedTraits: ['Tenacidad heroica', 'Rigor experimental', 'Desdén por el reconocimiento'],
    avatarUrl: '/assets/archetypes/curie.webp',
    traits: {
      openness: 90,
      conscientiousness: 98,
      extraversion: 30,
      agreeableness: 70,
      neuroticism: 35,
    },
  },
  {
    id: 'char_lord_byron',
    name: 'Lord Byron',
    origin: 'Poeta Romántico',
    type: 'historical',
    affinityPercentage: 87.8,
    sharedTraits: ['Pasión tempestuosa', 'Inconformismo aristocrático', 'Lirismo volcánico'],
    avatarUrl: '/assets/archetypes/byron.webp',
    traits: {
      openness: 92,
      conscientiousness: 35,
      extraversion: 85,
      agreeableness: 45,
      neuroticism: 85,
    },
  },
  {
    id: 'char_ada_lovelace',
    name: 'Ada Lovelace',
    origin: 'Primera Programadora de la Historia',
    type: 'historical',
    affinityPercentage: 93.5,
    sharedTraits: ['Ciencia poética', 'Pensamiento predictivo', 'Intuición algorítmica'],
    avatarUrl: '/assets/archetypes/lovelace.webp',
    traits: {
      openness: 96,
      conscientiousness: 88,
      extraversion: 60,
      agreeableness: 70,
      neuroticism: 50,
    },
  },
  {
    id: 'char_marcus_aurelius',
    name: 'Marco Aurelio',
    origin: 'Emperador y Filósofo Estoico',
    type: 'historical',
    affinityPercentage: 94.6,
    sharedTraits: ['Serenidad estoica', 'Deber público', 'Autocontrol meditativo'],
    avatarUrl: '/assets/archetypes/marcus.webp',
    traits: {
      openness: 85,
      conscientiousness: 95,
      extraversion: 40,
      agreeableness: 85,
      neuroticism: 20,
    },
  },
  {
    id: 'char_oscar_wilde',
    name: 'Oscar Wilde',
    origin: 'Dramaturgo y Ensayista',
    type: 'historical',
    affinityPercentage: 91.3,
    sharedTraits: ['Ironía brillante', 'Esteticismo desafiante', 'Elocuencia suprema'],
    avatarUrl: '/assets/archetypes/wilde.webp',
    traits: {
      openness: 98,
      conscientiousness: 45,
      extraversion: 90,
      agreeableness: 65,
      neuroticism: 60,
    },
  },
  {
    id: 'char_hypatia',
    name: 'Hipatia de Alejandría',
    origin: 'Filósofa y Astrónoma',
    type: 'historical',
    affinityPercentage: 92.0,
    sharedTraits: ['Devoción por la verdad', 'Elocuencia pedagógica', 'Claridad matemática'],
    avatarUrl: '/assets/archetypes/hypatia.webp',
    traits: {
      openness: 94,
      conscientiousness: 92,
      extraversion: 60,
      agreeableness: 80,
      neuroticism: 30,
    },
  },
  {
    id: 'char_albert_camus',
    name: 'Albert Camus',
    origin: 'Filósofo y Escritor',
    type: 'historical',
    affinityPercentage: 89.9,
    sharedTraits: ['Aceptación del absurdo', 'Rebelión humanista', 'Elegancia mediterránea'],
    avatarUrl: '/assets/archetypes/camus.webp',
    traits: {
      openness: 90,
      conscientiousness: 75,
      extraversion: 65,
      agreeableness: 75,
      neuroticism: 60,
    },
  },
  {
    id: 'char_jorge_luis_borges',
    name: 'Jorge Luis Borges',
    origin: 'Escritor y Poeta Argentino',
    type: 'historical',
    affinityPercentage: 94.7,
    sharedTraits: ['Laberintos metafísicos', 'Fascinación por el infinito', 'Laconismo sabio'],
    avatarUrl: '/assets/archetypes/borges.webp',
    traits: {
      openness: 99,
      conscientiousness: 80,
      extraversion: 30,
      agreeableness: 80,
      neuroticism: 40,
    },
  },
  {
    id: 'char_miles_davis',
    name: 'Miles Davis',
    origin: 'Trompetista de Jazz',
    type: 'historical',
    affinityPercentage: 90.2,
    sharedTraits: ['Innovación incesante', 'Elegancia lacónica', 'Dominio del silencio'],
    avatarUrl: '/assets/archetypes/miles.webp',
    traits: {
      openness: 96,
      conscientiousness: 80,
      extraversion: 60,
      agreeableness: 35,
      neuroticism: 65,
    },
  },
  {
    id: 'char_simone_de_beauvoir',
    name: 'Simone de Beauvoir',
    origin: 'Filósofa y Ensayista',
    type: 'historical',
    affinityPercentage: 91.5,
    sharedTraits: ['Lucidez existencial', 'Pensamiento emancipador', 'Firmeza intelectual'],
    avatarUrl: '/assets/archetypes/beauvoir.webp',
    traits: {
      openness: 95,
      conscientiousness: 85,
      extraversion: 65,
      agreeableness: 60,
      neuroticism: 45,
    },
  },
  {
    id: 'char_carl_sagan',
    name: 'Carl Sagan',
    origin: 'Astrofísico y Divulgador',
    type: 'historical',
    affinityPercentage: 96.1,
    sharedTraits: ['Asombro cósmico', 'Humanismo solidario', 'Claridad inspiradora'],
    avatarUrl: '/assets/archetypes/sagan.webp',
    traits: {
      openness: 98,
      conscientiousness: 88,
      extraversion: 80,
      agreeableness: 92,
      neuroticism: 20,
    },
  },
  {
    id: 'char_patti_smith',
    name: 'Patti Smith',
    origin: 'Poeta y Madrina del Punk',
    type: 'historical',
    affinityPercentage: 92.4,
    sharedTraits: ['Lirismo eléctrico', 'Devoción chamánica', 'Honestidad cruda'],
    avatarUrl: '/assets/archetypes/patti.webp',
    traits: {
      openness: 97,
      conscientiousness: 70,
      extraversion: 75,
      agreeableness: 80,
      neuroticism: 65,
    },
  },
  {
    id: 'char_jimi_hendrix',
    name: 'Jimi Hendrix',
    origin: 'Guitarrista Revolucionario',
    type: 'historical',
    affinityPercentage: 91.8,
    sharedTraits: ['Expansión sónica', 'Expresionismo psicodélico', 'Fusión instrumental'],
    avatarUrl: '/assets/archetypes/hendrix.webp',
    traits: {
      openness: 98,
      conscientiousness: 55,
      extraversion: 70,
      agreeableness: 75,
      neuroticism: 60,
    },
  },
  {
    id: 'char_emily_dickinson',
    name: 'Emily Dickinson',
    origin: 'Poeta Solitaria',
    type: 'historical',
    affinityPercentage: 88.7,
    sharedTraits: ['Introspección microscópica', 'Poder condensado', 'Silencio creador'],
    avatarUrl: '/assets/archetypes/dickinson.webp',
    traits: {
      openness: 95,
      conscientiousness: 80,
      extraversion: 10,
      agreeableness: 75,
      neuroticism: 70,
    },
  },
  {
    id: 'char_spinoza',
    name: 'Baruch Spinoza',
    origin: 'Filósofo de la Alegría',
    type: 'historical',
    affinityPercentage: 93.8,
    sharedTraits: ['Panteísmo racional', 'Tranquilidad sublime', 'Independencia moral'],
    avatarUrl: '/assets/archetypes/spinoza.webp',
    traits: {
      openness: 94,
      conscientiousness: 96,
      extraversion: 25,
      agreeableness: 85,
      neuroticism: 15,
    },
  },
  {
    id: 'char_sun_tzu',
    name: 'Sun Tzu',
    origin: 'Estratega Militar Antiguo',
    type: 'historical',
    affinityPercentage: 88.5,
    sharedTraits: ['Estrategia adaptativa', 'Economía del esfuerzo', 'Visión holística'],
    avatarUrl: '/assets/archetypes/suntzu.webp',
    traits: {
      openness: 85,
      conscientiousness: 96,
      extraversion: 40,
      agreeableness: 45,
      neuroticism: 20,
    },
  },
  {
    id: 'char_mary_shelley',
    name: 'Mary Shelley',
    origin: 'Creadora de Frankenstein',
    type: 'historical',
    affinityPercentage: 90.9,
    sharedTraits: ['Imaginación gótica', 'Reflexión tecnocientífica', 'Profundidad trágica'],
    avatarUrl: '/assets/archetypes/shelley.webp',
    traits: {
      openness: 96,
      conscientiousness: 75,
      extraversion: 45,
      agreeableness: 70,
      neuroticism: 80,
    },
  },
  {
    id: 'char_beethoven',
    name: 'Ludwig van Beethoven',
    origin: 'Compositor Clásico / Romántico',
    type: 'historical',
    affinityPercentage: 93.2,
    sharedTraits: ['Voluntad sobre el destino', 'Fuerza heroica', 'Evolución formal incesante'],
    avatarUrl: '/assets/archetypes/beethoven.webp',
    traits: {
      openness: 97,
      conscientiousness: 85,
      extraversion: 45,
      agreeableness: 35,
      neuroticism: 90,
    },
  },
  {
    id: 'char_hokusai',
    name: 'Katsushika Hokusai',
    origin: 'Maestro del Ukiyo-e',
    type: 'historical',
    affinityPercentage: 92.1,
    sharedTraits: [
      'Perfeccionismo hasta la vejez',
      'Dinamismo lineal',
      'Comunión con la naturaleza',
    ],
    avatarUrl: '/assets/archetypes/hokusai.webp',
    traits: {
      openness: 96,
      conscientiousness: 90,
      extraversion: 50,
      agreeableness: 80,
      neuroticism: 30,
    },
  },
] as const;
